<a href="https://colab.research.google.com/github/financieras/math/blob/main/algebra/determinantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Determinantes
Cálculo de determinantes con la librería ```numpy```

## Búsqueda de un determinante cero

In [12]:
import numpy as np

n = 6   # dimensión de la matriz cuadrada n×n
while True:
    # generación de una matriz de números aleatorios enteros entre -9 y +9
    m = np.random.randint(-9,10, size=(n,n))
    d = np.linalg.det(m)   # cálculo del determinante
    if abs(d) < 1e-6:      # no exigimos que sea exactamente igual a cero ya que existen pequeños errores
        print(m)
        print("Determinate:", d)
        print("Determinate redondeando:", abs(round(d,5)))
        break

[[-4  5  7  2 -3  5]
 [-7  2 -7 -7  5  8]
 [-5 -1  8  9  2  5]
 [ 8  4  2 -3 -1  7]
 [-5  6 -5 -3  3 -2]
 [ 9  1  4  2 -6 -8]]
Determinate: 0.0
Determinate redondeando: 0.0
