<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

# Ideas para la resolución de la Práctica 3.7

## Dada la matriz $A$ calcular sus autovalores y autovectores
* Los autovalores también se llaman eigenvalores o [eigenvalues](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors).
* Los autovectores también se llaman [eigenvectores](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios) o eigenvectors.


Para nuestro ejemplo vamos a utilizar la siguiente matriz $A$:

$$A=\left(
\begin{array}{rrrr}
 -3 & 2 & 0 &  0 \\
 -3 & 4 & 0 &  0 \\
  0 & 0 &-5 & -4 \\
  0 & 0 &-2 &  2
\end{array}
\right)$$

Cálculo manual de los autovalores: [Encuentre los valores propios de una matriz 4x4](https://youtu.be/iJU78zgRpJ0)

## Trabajando con la librería ```NumPy```

In [ ]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)

d:  [-2.  3. -6.  3.]

D:
 [[-2.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0.  3.]]

P:
 [[-0.89442719 -0.31622777  0.          0.        ]
 [-0.4472136  -0.9486833   0.          0.        ]
 [ 0.          0.         -0.9701425   0.4472136 ]
 [ 0.          0.         -0.24253563 -0.89442719]]


## Trabajando con la librería ```Sympy```

In [ ]:
`from sympy import Matrix
A = Matrix([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
P, D = A.diagonalize()
D

Matrix([
[-6,  0, 0, 0],
[ 0, -2, 0, 0],
[ 0,  0, 3, 0],
[ 0,  0, 0, 3]])

In [ ]:
P

Matrix([
[0, 2, 1,  0],
[0, 1, 3,  0],
[4, 0, 0, -1],
[1, 0, 0,  2]])

## Calculando $A^3$

In [ ]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
print(A@A@A)

[[ -15   14    0    0]
 [ -21   34    0    0]
 [   0    0 -189 -108]
 [   0    0  -54    0]]


## Calculando $PD^3P^{-1}$

In [ ]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))

d:  [-2.  3. -6.  3.]

D:
 [[-2.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0.  3.]]

P:
 [[-0.89442719 -0.31622777  0.          0.        ]
 [-0.4472136  -0.9486833   0.          0.        ]
 [ 0.          0.         -0.9701425   0.4472136 ]
 [ 0.          0.         -0.24253563 -0.89442719]]

Dcubo:
 [[  -8.    0.    0.    0.]
 [   0.   27.    0.    0.]
 [   0.    0. -216.    0.]
 [   0.    0.    0.   27.]]

Solución:
 [[-1.50000000e+01  1.40000000e+01  0.00000000e+00  0.00000000e+00]
 [-2.10000000e+01  3.40000000e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.89000000e+02 -1.08000000e+02]
 [ 0.00000000e+00  0.00000000e+00 -5.40000000e+01 -2.74319149e-15]]
