<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

# Ideas para la resolución de la Práctica 3.7

## Dada la matriz $A$ calcular sus autovalores y autovectores
* Los autovalores también se llaman eigenvalores o [eigenvalues](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors).
* Los autovectores también se llaman [eigenvectores](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios) o eigenvectors.

In [26]:
from numpy.linalg import inv
from sympy import Matrix
A = Matrix([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
P, D = M.diagonalize()

print(f"Matriz diagonal D:\n{D}")
print()

print(f"Matriz de paso P:\n{P}")

print("A*A*A\n", A*A*A)
print("A @ A @ A\n", A@A@A)
print()
D3 = Matrix([[-2**3, 0, 0, 0], [0, 3**3, 0, 0], [0, 0, 5**3, 0], [0, 0, 0, 5**3]])
print("D3\n", D3)
Pinv = P.inv()
print("inv(P)", Pinv)
print(P@D3@Pinv)

Matriz diagonal D:
Matrix([[-2, 0, 0, 0], [0, 3, 0, 0], [0, 0, 5, 0], [0, 0, 0, 5]])

Matriz de paso P:
Matrix([[0, 1, 1, 0], [1, 1, 1, -1], [1, 1, 1, 0], [1, 1, 0, 1]])
A*A*A
 Matrix([[-1, -6, 9, -1], [0, 8, 0, 0], [0, 0, 8, 0], [0, 0, 0, 1]])
A @ A @ A
 Matrix([[-1, -6, 9, -1], [0, 8, 0, 0], [0, 0, 8, 0], [0, 0, 0, 1]])

D3
 Matrix([[-8, 0, 0, 0], [0, 27, 0, 0], [0, 0, 125, 0], [0, 0, 0, 125]])
inv(P) Matrix([[-1, 0, 1, 0], [1, 1, -2, 1], [0, -1, 2, -1], [0, -1, 1, 0]])
Matrix([[27, -98, 196, -98], [35, 27, 63, -98], [35, -98, 188, -98], [35, -98, 63, 27]])


In [24]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
print(A @ A @ A)

[[-1 -6  9 -1]
 [ 0  8  0  0]
 [ 0  0  8  0]
 [ 0  0  0  1]]


In [2]:
import numpy as np
A = [[3, 2, -1], [2, 3, 1], [0, 0, 5]]

np.linalg.eig(A)
w,v = np.linalg.eig(A)
print('E-value:', w)
print('E-vector\n', v)

E-value: [5. 1. 5.]
E-vector
 [[ 0.70710678 -0.70710678 -0.10059617]
 [ 0.70710678  0.70710678  0.36264488]
 [ 0.          0.          0.92648211]]


In [11]:
from sympy import * 
M = Matrix([[3, 2, -1], [2, 3, 1], [0, 0, 5]])

print(f"Matriz:\n{M}")
print()

# Use sympy.diagonalize() method
P, D = M.diagonalize()

print(f"Matriz diagonal D:\n{D}")
print()

print(f"Matriz de paso P:\n{P}")

Matriz:
Matrix([[3, 2, -1], [2, 3, 1], [0, 0, 5]])

Matriz diagonal D:
Matrix([[1, 0, 0], [0, 5, 0], [0, 0, 5]])

Matriz de paso P:
Matrix([[-1, 1, -1], [1, 1, 0], [0, 0, 2]])


In [ ]:
#   https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.04-Eigenvalues-and-Eigenvectors-in-Python.html
#   https://www.geeksforgeeks.org/python-sympy-matrix-diagonalize-method/
from sympy import * 
M = Matrix([[3, -2, 4, -2],
			[5, 3, -3, -2],
			[5, -2, 2, -2],
			[5, -2, -3, 3]])

print(f"Matriz:\n{M}")
print()

# Use sympy.diagonalize() method
P, D = M.diagonalize()
	
print(f"Matriz diagonal D:\n{D}")

In [16]:
import numpy as np
from sympy import * 
A = [[5, 4, -10], [3, 4, -8],[ 3, 3, -7]]
np.linalg.eig(A)
w,v = np.linalg.eig(A)
print('E-value:', w)
print('E-vector\n', v)
print()

M = Matrix(A)
P, D = M.diagonalize()

print(f"Matriz diagonal D:\n{D}")
print()

print(f"Matriz de paso P:\n{P}")


E-value: [-1.  2.  1.]
E-vector
 [[ 5.77350269e-01  8.16496581e-01  7.07106781e-01]
 [ 5.77350269e-01  4.08248290e-01 -7.07106781e-01]
 [ 5.77350269e-01  4.08248290e-01  2.77555756e-16]]

Matriz diagonal D:
Matrix([[-1, 0, 0], [0, 1, 0], [0, 0, 2]])

Matriz de paso P:
Matrix([[1, -1, 2], [1, 1, 1], [1, 0, 1]])
