<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

# Ideas para la resolución de la Práctica 3.10
* Mire este vídeo: [Cadenas de Markov](https://youtu.be/hQYXcX3KHVE)
* Vea el documento [Diagonalización](https://www.dropbox.com/s/5v7kf1zkbltwf6b/Diagonalizacion.pdf?dl=1)  

<img src="https://github.com/financieras/math/blob/main/img/grafo_markov10.png?raw=1" alt="grafo" width="300">


* Ventas = 100.000
* Vector de estado inicial $\begin{align*}
    X_0 &= \begin{pmatrix}
           0.75 \\
           0.25
         \end{pmatrix}
  \end{align*}$
* Matriz de transición $\begin{align*}
    A &= \begin{pmatrix}
           0.80 & 0.40 \\
           0.20 & 0.60
         \end{pmatrix}
  \end{align*}$
* Estado a los tres años $$X_3 = A^3 X_0 = \begin{align*}
    \begin{pmatrix}
           0.80 & 0.40 \\
           0.20 & 0.60
         \end{pmatrix}^3
    \begin{pmatrix}
           0.75 \\
           0.25
         \end{pmatrix} = 
    \begin{pmatrix}
           0.688 & 0.624 \\
           0.312 & 0.376
         \end{pmatrix}
    \begin{pmatrix}
           0.75 \\
           0.25
         \end{pmatrix} =
        \begin{pmatrix}
           0.672 \\
           0.328
         \end{pmatrix}
  \end{align*}$$

* Estado a los veinte años $$X_{20} = A^{20} X_0 = \begin{align*}
    \begin{pmatrix}
           0.80 & 0.40 \\
           0.20 & 0.60
         \end{pmatrix}^{20}
    \begin{pmatrix}
           0.75 \\
           0.25
         \end{pmatrix} = 
    \begin{pmatrix}
           ^2/_3 \\
           ^1/_3
         \end{pmatrix}
  \end{align*}$$

In [15]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)
A10 = P@(D**10)@Pinv
X10 = A10@X0
print("Situación a los diez años:", X10)
print("Situación a los veinte años:", P@(D**20)@Pinv@X0)

Situación a los tres años: [0.672 0.328]
Situación a los diez años: [0.6666754 0.3333246]
Situación a los veinte años: [0.66666667 0.33333333]


In [16]:
# A cubo
A@A@A

array([[0.688, 0.624],
       [0.312, 0.376]])

In [17]:
# comprobación de que esta expresión es igual a A cubo
P@(D**3)@Pinv

array([[0.688, 0.624],
       [0.312, 0.376]])

In [18]:
A@A@A@A@A@A@A@A@A@A

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [19]:
P@(D**10)@Pinv

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [20]:
np.round(A@A@A@A@A@A@A@A@A@A, 12) == np.round(P@(D**10)@Pinv, 12)

array([[ True,  True],
       [ True,  True]])