<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

# Ideas para la resolución de la Práctica 3.7

## Dada la matriz $A$ calcular sus autovalores y autovectores
* Los autovalores también se llaman eigenvalores o [eigenvalues](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors).
* Los autovectores también se llaman [eigenvectores](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios) o eigenvectors.

## Trabajando con Octave

In [ ]:
!apt install octave
!apt update

In [4]:
%%writefile diagonaliza.m
A = [3,0,0; 0,2,1; 0,1,2]
[P,D]=eig(A)

Overwriting diagonaliza.m


In [5]:
!octave diagonaliza.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
A =

   3   0   0
   0   2   1
   0   1   2

P =

   0.00000   0.00000   1.00000
  -0.70711   0.70711   0.00000
   0.70711   0.70711   0.00000

D =

Diagonal Matrix

   1   0   0
   0   3   0
   0   0   3



## con NumPy

In [7]:
import numpy as np
A = np.array([[3,0,0], [0,2,1], [0,1,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)

d:  [3. 1. 3.]

D:
 [[3. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]

P:
 [[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]


## con Sympy

In [17]:
from sympy import Matrix
A = Matrix([[3,0,0], [0,2,1], [0,1,2]])
P, D = A.diagonalize()

print(f"Matriz diagonal D:\n{D}")
print()

print(f"Matriz de paso P:\n{P}")

Matriz diagonal D:
Matrix([[1, 0, 0], [0, 3, 0], [0, 0, 3]])

Matriz de paso P:
Matrix([[0, 1, 0], [-1, 0, 1], [1, 0, 1]])


## calculando $A^3$

In [9]:
import numpy as np
A = np.array([[3,0,0], [0,2,1], [0,1,2]])
print(A@A@A)

[[27  0  0]
 [ 0 14 13]
 [ 0 13 14]]


## calculando $PD^3P^{-1}$

In [12]:
import numpy as np
A = np.array([[3,0,0], [0,2,1], [0,1,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))

d:  [3. 1. 3.]

D:
 [[3. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]

P:
 [[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]

Dcubo:
 [[27.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. 27.]]

Solución:
 [[27.  0.  0.]
 [ 0. 14. 13.]
 [ 0. 13. 14.]]
