<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ideas para la resolución de la Práctica 3.4

## Aleatorio entre 0 y 1
Generar un número aleatorio en Python que se distribuya según la distribución Uniforme [0,1)

### Método 1

In [ ]:
import random
random.seed()
rnd = random.random()
print("Número aleatorio entre 0 y 1: ", rnd)

Número aleatorio entre 0 y 1:  0.5135725626535593


### Método 2

In [ ]:
from random import random, seed
seed()
print("Número aleatorio entre 0 y 1: ", random())

Número aleatorio entre 0 y 1:  0.4405908848914649


## Aleatorio entre -9 y +9
Generar un número aleatorio entre -9 y +9, donde puedan estar ambos incluidos.

### Método 1

In [ ]:
from random import randint
print(randint(-9, 9))

9


### Método 2
 Usamos la uniforma (0,1) multiplicada por un número (la amplitud del intervalo) y más o menos otro valor, para que se ajuste al rango pedido. Y sobre ello se toma la parte entera con ```int```.  
Para comprobar que abarcamos el rango indicado generamos un gran número de valores y calculamos el mínimo y el máximo. De esta forma comprobamos que estamos entre -9 y +9.

In [ ]:
from random import random, seed
seed()
lista = []
for i in range(100_000):
    rnd = int(random()*19)-9
    lista.append(rnd)
print(min(lista))
print(max(lista))

-9
9


## Elegir aleatoriamente un elemento de una lista

In [ ]:
import random
random.choice([1,2,3,4])

3

## Aleatorio entre -9 y +9, salvo 0

In [ ]:
#@title
from random import randint, choice
randint(1,9) * choice([1,-1])

## Tiempo que tarda un proceso
En segundos.

In [ ]:
from time import process_time

t1 = process_time()

for i in range(10_000_000):
    cuadrado = i**2

t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")

El proceso ha tardado 3.108162828000001 segundos.


## Bucle ```while True```
Un bucle que se repite indefinidamente hasta encontrar un ```break```.

In [ ]:
import random

contador = 0
valor_deseado = 0

while True:
    rnd = random.choice(list(range(1000)))
    contador += 1
    if rnd == valor_deseado:
        print(f"Se han realizado {contador} ciclos en el bucle hasta encontrar el valor deaseado.")
        break

print("Fin del programa")

Se han realizado 1118 ciclos en el bucle hasta encontrar el valor deaseado.
Fin del programa


## Inicializar una lista

### Método 1

In [ ]:
l = [0]*5
l

[0, 0, 0, 0, 0]

### Método 2

In [ ]:
l = [None]*5
l

[None, None, None, None, None]

## Copiar una lista

### Método incorrecto
La lista b no es una copia de a sino que sigue siendo a.  
Al cambiar un valor de a tambien cambia en b, no son independientes.

In [ ]:
a = [1,2,3]
b = a
a[0] = 10
print(b)

[10, 2, 3]


### Método correcto

In [ ]:
a = [1,2,3]
b = a[:]
c = a.copy()
a[0] = 10
print(b)
print(c)

[1, 2, 3]
[1, 2, 3]


## List Comprehension

In [ ]:
cuadrados = [i**2 for i in range(1,11)]
cuadrados

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [1]:
ciudades = ['Madrid', 'Oviedo', 'Sevilla', 'Lugo']
[c for c in ciudades if 'a' in c]

['Madrid', 'Sevilla']

## Matriz de números aleatorios

### Método 1

In [5]:
from random import randint, seed
seed()
m = []
for i in range(5):
    fila = []
    for j in range(5):
        fila.append(randint(0,9))
    m.append(fila)

m 


[[8, 3, 1, 3, 5],
 [0, 0, 5, 3, 7],
 [2, 6, 1, 8, 6],
 [4, 7, 1, 2, 9],
 [4, 3, 8, 6, 8]]

### Método 2

In [7]:
[[randint(0,9) for j in range(5)] for i in range(5)]

[[7, 4, 7, 6, 1],
 [6, 9, 4, 6, 5],
 [4, 9, 9, 8, 8],
 [4, 5, 9, 4, 6],
 [5, 5, 2, 4, 7]]

## Convertir una lista en un ndarray usando ```Numpy```

In [11]:
import numpy as np

lista = [1,2,3,4]
vector = np.array(lista)   # convertimos la matriz en un ndarray
vector

array([1, 2, 3, 4])

## Ventajas de un ndarray frente a una lista
La gran ventaja es que con los ndarray se puede operar como si estuviérasmos tratando con vectores de álgebra.  
* Se pueden sumar vectores. Si fueran dos listas no se suman, se añaden elementos.
* Se pueden multipicar matrices

In [12]:
lista1 = [1,2,3]
lista2 = [4,5,6]
vector1 = np.array(lista1)
vector2 = np.array(lista2)
print("Suma de listas", lista1 + lista2)
print("Suma de vectores", vector1 + vector2)

Suma de listas [1, 2, 3, 4, 5, 6]
Suma de vectores [5 7 9]


In [66]:
import numpy as np
m = [[1,2,3], [4,5,6], [7,8,9]]
b = [1,-2,2]
#print("El producto con listas da error", m*b )
m = np.array(m)
b = np.array(b)
print("Producto con nd arrays\n", np.dot(m,b))

Producto con nd arrays
 [3 6 9]


## Determinante con ```Numpy```

In [17]:
import numpy as np
m = [[1,-2,3], [4,5,6], [7,8,0]]
np.linalg.det(m)

-141.00000000000003

## Típio error de redondeo al operar con números ```float```

In [18]:
print(0.1 + 0.1 + 0.1)

0.30000000000000004


## Redondear

In [55]:
import math
print("pi: ", math.pi)
print(f"Redondeando: {round(math.pi, 4)}")

pi:  3.141592653589793
Redondeando: 3.1416


## Matriz de números aleatorios con determinante nulo

In [46]:
import numpy as np

n = 5   # orden nxn de la matriz cuadrada

while True:
    m = np.random.randint(-9,10, size=(n, n))   # aleatorios enteros entre -9 y +9
    if np.linalg.det(m) == 0:
        print(m)
        break

[[ 3  6  4  3  7]
 [-1 -4  0 -3  7]
 [ 3  6  4  3  7]
 [-8 -1 -1 -1 -9]
 [ 8 -1  4  8 -5]]


## Transponer una matriz con ```NumPy```

In [59]:
import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz:")
print(m)
print("\nTasnpuesta:")
print(np.transpose(m))

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Tasnpuesta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Inversa de una mariz con ```NumPy```

In [65]:
import numpy as np
m = np.array([[1,-7, -8], [ 1,-4,-4], [-1,3,3]])
print("Matriz:")
print(m)
print()
print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()
print("Matriz Identidad:")
print(np.dot(m, minv))

Matriz:
[[ 1 -7 -8]
 [ 1 -4 -4]
 [-1  3  3]]

Inversa:
[[ 0. -3. -4.]
 [ 1. -5. -4.]
 [-1.  4.  3.]]

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
