<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ideas para la resolución de la Práctica 3.5

## Elegir aleatoriamente un número de una lista
* Elegimos 3 números de una lista
* Los números elegidos se pueden repetir

### Método 1

In [ ]:
import numpy as np
np.random.choice([0,1,2,3,4,5,6,7,8,9], 3)

array([6, 3, 4])

### Método 2

In [ ]:
import numpy as np
np.random.choice(range(10), 3)

array([5, 8, 2])

## Concatenar dos listas
Los números del -9 al 9 salvo el 0.

In [ ]:
list(range(-9,0)) + list(range(1,10))

[-9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Buscar vector
Buscar un vector $w$ que al multiplicarlo por otro vector conocido $v$ nos de cierto número $b$ también conocido.

* Vamos a crear una función en Python que busque ese vector $w$.
* La función usa $b$ como parámetro.
* El parámetro $b$ es el número buscado que es igual al producto de los dos vectores.
* Uno de los vectores es conocido $v=(1,2,4,3)$
* El otro vector es $w$ y es el que queremos buscar.
* La función retornará el vector $w$ cuando lo encuentre.
* Existen muchísimas soluciones para $w$ por lo que vamos a restringirlo para que los elementos que componen el vector sean números enteros no muy grandes, por ejemplo entre -5 y +5 excluido el cero.
* Los elementos de $w$ se eligen aleatoriamente hasta encontrar uno que cumpla los requisitos que le hemos impuesto.


In [9]:
import numpy as np

v = np.array([1,2,4,3])   # vector conocido, supongamos que es la solución de sistema lineal

def busca(b):
    while True:
        w = np.random.choice(list(range(-5,0))+list(range(1,6)), 4)
        if np.matmul(v, w) == b:   # el producto de los dos vectores debe ser igual a número b
            break
    return w

b = 5; print(f"{busca(b)} x {v} = {b}")
b = -3; print(f"{busca(b)} x {v} = {b}")
b = -1; print(f"{busca(b)} x {v} = {b}")
b = -2; print(f"{busca(b)} x {v} = {b}")
# Multiplicando a mano el primer vector sería un vector fila y
# el segundo un vector columna
# Al usar NumPy no nos preocupamos de la congruendia de vectores

[-4  2  2 -1] x [1 2 4 3] = 5
[ 4 -3 -4  5] x [1 2 4 3] = -3
[ 4 -2  2 -3] x [1 2 4 3] = -1
[-5 -2  4 -3] x [1 2 4 3] = -2


## Construir una matriz conocidas sus filas


In [10]:
import numpy as np

f1 = [-4, -2, 4,  2]
f2 = [-5,  2,  4, -5]
f3 = [-5, 5, -3,  4]
f4 = [2,  2, -1, -5]
matriz = [f1, f2, f3, f4]
print(matriz)
print()

# m es un ndarray (n dimensional array)
m = np.array(matriz)
m

[[-4, -2, 4, 2], [-5, 2, 4, -5], [-5, 5, -3, 4], [2, 2, -1, -5]]



array([[-4, -2,  4,  2],
       [-5,  2,  4, -5],
       [-5,  5, -3,  4],
       [ 2,  2, -1, -5]])