<a href="https://colab.research.google.com/github/financieras/math/blob/main/ideas/ideas3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ideas para la resolución de la Práctica 3.5

## Elegir aleatoriamente un número de una lista
* Elegimos 3 números de una lista
* Los números elegidos se pueden repetir

### Método 1

In [8]:
import numpy as np
np.random.choice([0,1,2,3,4,5,6,7,8,9], 3)

array([6, 3, 4])

### Método 2

In [17]:
import numpy as np
np.random.choice(range(10), 3)

array([5, 8, 2])

## Concatenar dos listas
Los números del -9 al 9 salvo el 0.

In [18]:
list(range(-9,0)) + list(range(1,10))

[-9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Buscar vector
Buscar un vector que al multiplicarse por otro nos de ciero número.

In [20]:
import numpy as np

a = np.array([3,4,5,2])


def busca(b):
    while True:
        fila = np.random.choice(list(range(-5,0))+list(range(1,6)), 4)
        if np.matmul(a, fila) == b:
            break
    return fila

print(busca(6))
print(busca(8))
print(busca(10))

[-5  5  1 -2]
[-1 -4  5  1]
[ 3 -4  3  1]
